"""
visualizer.py — pygame HDMI display: waveform + FFT spectrum + function-gen controls.

Two full-screen views, toggled by the SPECTRUM / CONTROLS tab buttons in the header
(or press Tab on the keyboard):

  SPECTRUM  — waveform + FFT + display sliders (original view)
  CONTROLS  — function generator: 4 voice rows + master volume + clip gain

Mouse:
  Click [SPECTRUM] / [CONTROLS] tab buttons  → switch view
  Tab key                                    → switch view
  Drag slider handle                         → adjust value (commands sent live)
  Click wave-type button                     → select waveform for a voice
  Click [STOP N]                             → silence that voice
  Click [STOP ALL]                           → silence all voices
  Left click (spectrum background)           → pause / resume
  Right click / ESC / Q                      → quit

Commands generated by the controls view are queued and returned by
get_pending_commands() each frame; main.py forwards them to the ESP32 via UDP.
"""

import math
from enum import Enum

import numpy as np
import pygame

# ── Colours ───────────────────────────────────────────────────────────────────
BG        = (  5,   5,  15)
GRID      = ( 25,  25,  45)
ACCENT    = ( 60, 100, 220)
WAVE_COL  = (  0, 230, 180)   # cyan-green
FFT_COL   = (220,  40, 180)   # magenta
TEXT_COL  = (180, 180, 210)
TITLE_COL = (240, 240, 255)
BTN_COL   = ( 35,  35,  60)   # inactive button background
BTN_HOV   = ( 55,  75, 155)   # hovered
STOP_COL  = (130,  20,  20)
STOP_HOV  = (200,  50,  50)
TRIG_COL  = (255, 200,   0)   # yellow trigger marker

TITLE      = "BSc Analog Electronics — Real-Time Audio Spectrum"
DB_MIN     = -80.0
DB_MAX     =   0.0
LABEL_PAD  =  48
FREQ_TICKS = (200, 500, 1000, 2000, 4000, 6000, 8000, 10000, 15000, 20000)
WAVE_TYPES = ("SINE", "SQUARE", "TRIANGLE", "SAW")

WAVE_COLORS = {
    "SINE":     (  0, 210, 160),
    "SQUARE":   (220, 160,   0),
    "TRIANGLE": ( 80, 180, 255),
    "SAW":      (210,  70, 210),
}


class Screen(Enum):
    SPECTRUM = 0
    CONTROLS = 1


# ── Button ────────────────────────────────────────────────────────────────────
class Button:
    """Clickable rectangular button with hover highlight.

    handle_event() returns True on MOUSEBUTTONDOWN click.
    draw() renders the button; pass override_active to force lit-up state.
    """
    _RADIUS = 6

    def __init__(self, rect: pygame.Rect, label: str,
                 color=None, active_color=None, text_color=None):
        self.rect         = rect
        self.label        = label
        self._color       = color        or BTN_COL
        self._active_col  = active_color or ACCENT
        self._text_color  = text_color   or TEXT_COL
        self.active       = False
        self._hovered     = False

    def handle_event(self, ev: pygame.event.Event) -> bool:
        """Return True if this button was clicked (MOUSEBUTTONDOWN, button 1)."""
        if ev.type == pygame.MOUSEMOTION:
            self._hovered = self.rect.collidepoint(ev.pos)
        elif ev.type == pygame.MOUSEBUTTONDOWN and ev.button == 1:
            if self.rect.collidepoint(ev.pos):
                return True
        return False

    def draw(self, surface: pygame.Surface, font: pygame.font.Font,
             override_active: bool | None = None) -> None:
        active = self.active if override_active is None else override_active
        if active:
            bg = self._active_col
            tc = TITLE_COL
        elif self._hovered:
            bg = BTN_HOV
            tc = TITLE_COL
        else:
            bg = self._color
            tc = self._text_color
        pygame.draw.rect(surface, bg, self.rect, border_radius=self._RADIUS)
        pygame.draw.rect(surface, ACCENT, self.rect, 1, border_radius=self._RADIUS)
        lbl = font.render(self.label, True, tc)
        surface.blit(lbl, lbl.get_rect(center=self.rect.center))


# ── Slider ────────────────────────────────────────────────────────────────────
class Slider:
    """Horizontal draggable slider.

    handle_event() returns True whenever the value changed.
    """
    _TRACK_H  = 4
    _HANDLE_R = 9

    def __init__(self, rect: pygame.Rect, label: str,
                 min_val: float, max_val: float, init_val: float,
                 log: bool = False, fmt: str = "{:.2g}", unit: str = ""):
        self.rect      = rect
        self.label     = label
        self.min_val   = float(min_val)
        self.max_val   = float(max_val)
        self._value    = float(init_val)
        self.log       = log
        self.fmt       = fmt
        self.unit      = unit
        self._dragging = False
        if log:
            self._lmin = math.log(min_val)
            self._lmax = math.log(max_val)

    def _track_y(self) -> int:
        return self.rect.top + int(self.rect.height * 0.72)

    @property
    def value(self) -> float:
        return self._value

    @property
    def int_value(self) -> int:
        return int(round(self._value))

    def _frac(self) -> float:
        if self.log:
            return (math.log(max(self._value, self.min_val)) - self._lmin) / (self._lmax - self._lmin)
        return (self._value - self.min_val) / (self.max_val - self.min_val)

    def _handle_pos(self) -> tuple[int, int]:
        x = int(self.rect.left + self._frac() * self.rect.width)
        return (x, self._track_y())

    def _x_to_val(self, x: int) -> float:
        frac = max(0.0, min(1.0, (x - self.rect.left) / self.rect.width))
        if self.log:
            return math.exp(self._lmin + frac * (self._lmax - self._lmin))
        return self.min_val + frac * (self.max_val - self.min_val)

    def handle_event(self, ev: pygame.event.Event) -> bool:
        """Return True when value changes."""
        if ev.type == pygame.MOUSEBUTTONDOWN and ev.button == 1:
            hx, hy = self._handle_pos()
            if math.hypot(ev.pos[0] - hx, ev.pos[1] - hy) <= self._HANDLE_R + 8:
                self._dragging = True
                self._value = self._x_to_val(ev.pos[0])
                return True
        elif ev.type == pygame.MOUSEMOTION and self._dragging:
            self._value = self._x_to_val(ev.pos[0])
            return True
        elif ev.type == pygame.MOUSEBUTTONUP and ev.button == 1 and self._dragging:
            self._dragging = False
            return True
        return False

    def draw(self, surface: pygame.Surface, font: pygame.font.Font) -> None:
        hx, hy = self._handle_pos()
        tx0 = self.rect.left
        tx1 = self.rect.right
        pygame.draw.line(surface, GRID,   (tx0, hy), (tx1, hy), self._TRACK_H)
        pygame.draw.line(surface, ACCENT, (tx0, hy), (hx,  hy), self._TRACK_H)
        col = WAVE_COL if self._dragging else ACCENT
        pygame.draw.circle(surface, col, (hx, hy), self._HANDLE_R)
        val_str = self.fmt.format(self._value) + self.unit
        lbl = font.render(f"{self.label}:  {val_str}", True, TEXT_COL)
        surface.blit(lbl, (tx0, self.rect.top + 4))


# ── VoiceRow ──────────────────────────────────────────────────────────────────
class VoiceRow:
    """One function-generator voice row.

    Contains:
      * 4 waveform-type toggle buttons (SINE / SQUARE / TRIANGLE / SAW)
      * Frequency slider  (20 Hz – 20 kHz, log)
      * Amplitude slider  (0.0 – 1.0, linear)
      * STOP N button

    handle_event() returns a list of command strings to send to the ESP32.
    Commands are sent live (on every slider change) for real-time feedback.
    """

    def __init__(self, n: int, rect: pygame.Rect):
        self.n    = n        # 1-based voice number
        self.rect = rect

        pad   = 8
        btn_h = min(rect.height - 2 * pad, 44)
        btn_y = rect.centery - btn_h // 2

        # ── Voice label column ────────────────────────────────────────────────
        label_w = 56
        x = rect.left + label_w + 10

        # ── Wave type buttons (4 × 88 px with 6 px gap) ──────────────────────
        w_btn = 88
        gap   = 6
        self._wave_btns: list[Button] = []
        for i, wt in enumerate(WAVE_TYPES):
            bx = x + i * (w_btn + gap)
            b  = Button(
                pygame.Rect(bx, btn_y, w_btn, btn_h),
                wt,
                color=BTN_COL,
                active_color=WAVE_COLORS[wt],
            )
            b.active = (i == 0)   # SINE active by default
            self._wave_btns.append(b)
        x += len(WAVE_TYPES) * (w_btn + gap) + 20

        # ── Frequency slider ──────────────────────────────────────────────────
        avail  = rect.right - x - 100 - 12   # 100 reserved for stop btn + gap
        freq_w = int(avail * 0.55)
        self._freq_slider = Slider(
            pygame.Rect(x, btn_y - 4, freq_w, btn_h + 8),
            label="Freq", min_val=20.0, max_val=20000.0, init_val=440.0,
            log=True, fmt="{:.0f}", unit=" Hz",
        )
        x += freq_w + 14

        # ── Amplitude slider ──────────────────────────────────────────────────
        amp_w = int((rect.right - x - 100 - 12) * 0.92)
        self._amp_slider = Slider(
            pygame.Rect(x, btn_y - 4, amp_w, btn_h + 8),
            label="Amp", min_val=0.0, max_val=1.0, init_val=0.5,
            fmt="{:.2f}",
        )
        x += amp_w + 14

        # ── Stop button ───────────────────────────────────────────────────────
        stop_w = max(86, rect.right - x - 8)
        self._stop_btn = Button(
            pygame.Rect(x, btn_y, stop_w, btn_h),
            f"STOP {n}",
            color=STOP_COL, active_color=STOP_HOV,
        )

        self._selected_wave = 0   # index into WAVE_TYPES

    # ── helpers ───────────────────────────────────────────────────────────────

    @property
    def wave(self) -> str:
        return WAVE_TYPES[self._selected_wave]

    def _wave_cmd(self) -> str:
        return (f"WAVE{self.n} {self.wave} "
                f"{int(self._freq_slider.value)} "
                f"{self._amp_slider.value:.2f}")

    # ── public API ────────────────────────────────────────────────────────────

    def handle_event(self, ev: pygame.event.Event) -> list[str]:
        """Return list of ESP32 command strings triggered by this event."""
        cmds: list[str] = []

        # Wave type buttons
        for i, btn in enumerate(self._wave_btns):
            if btn.handle_event(ev):
                self._selected_wave = i
                for j, b in enumerate(self._wave_btns):
                    b.active = (j == i)
                cmds.append(self._wave_cmd())

        # Sliders — send live so frequency drags give real-time audio feedback
        if self._freq_slider.handle_event(ev):
            cmds.append(self._wave_cmd())
        if self._amp_slider.handle_event(ev):
            cmds.append(self._wave_cmd())

        # Stop button
        if self._stop_btn.handle_event(ev):
            cmds.append(f"STOP{self.n}")

        return cmds

    def draw(self, surface: pygame.Surface,
             font_lg: pygame.font.Font, font_sm: pygame.font.Font) -> None:
        # Row separator line
        pygame.draw.line(surface, GRID,
                         (self.rect.left,  self.rect.top),
                         (self.rect.right, self.rect.top))

        # Voice number label coloured to match the selected wave type
        col = WAVE_COLORS[self.wave]
        lbl = font_lg.render(f"V{self.n}", True, col)
        surface.blit(lbl, (self.rect.left + 8,
                            self.rect.centery - lbl.get_height() // 2))

        for btn in self._wave_btns:
            btn.draw(surface, font_sm)

        self._freq_slider.draw(surface, font_sm)
        self._amp_slider.draw(surface, font_sm)
        self._stop_btn.draw(surface, font_sm)


# ── ControlsScreen ────────────────────────────────────────────────────────────
class ControlsScreen:
    """Function-generator control panel.

    Layout (inside the area below the shared header):
      * 4 voice rows stacked evenly
      * Bottom bar: Master Volume slider | Mic Gain slider | STOP ALL button
    """

    _BOT_H = 90   # height of the master-controls bar

    def __init__(self, W: int, H: int, hdr_h: int):
        self.W = W
        self.H = H

        inner_h = H - hdr_h - self._BOT_H
        row_h   = inner_h // 2
        pad     = 6

        self.voices: list[VoiceRow] = []
        for i in range(2):
            r = pygame.Rect(pad, hdr_h + i * row_h,
                            W - 2 * pad, row_h)
            self.voices.append(VoiceRow(i + 1, r))

        # ── Bottom master-controls bar ────────────────────────────────────────
        bot_y      = H - self._BOT_H
        self._bot_y = bot_y

        s_pad  = 40
        s_gap  = 30
        btn_w  = 140
        s_y    = bot_y + 8
        s_h    = self._BOT_H - 14
        s_w    = (W - 2 * s_pad - 2 * s_gap - btn_w - 20) // 3

        x = s_pad
        self._vol_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="Volume", min_val=0.0, max_val=100.0, init_val=75.0,
            fmt="{:.0f}", unit="%",
        )
        x += s_w + s_gap
        self._clip_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="Mic gain", min_val=0.5, max_val=4.0, init_val=1.0,
            fmt="{:.2f}", unit="x",
        )
        x += s_w + s_gap
        self._bw_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="BW limit", min_val=500.0, max_val=20000.0, init_val=20000.0,
            log=True, fmt="{:.0f}", unit=" Hz",
        )
        x += s_w + s_gap
        self._stop_all_btn = Button(
            pygame.Rect(x, bot_y + (self._BOT_H - 48) // 2, btn_w, 48),
            "STOP ALL",
            color=STOP_COL, active_color=STOP_HOV,
        )

    def handle_event(self, ev: pygame.event.Event) -> list[str]:
        cmds: list[str] = []
        for voice in self.voices:
            cmds.extend(voice.handle_event(ev))
        if self._vol_slider.handle_event(ev):
            cmds.append(f"VOLUME {self._vol_slider.int_value}")
        if self._clip_slider.handle_event(ev):
            cmds.append(f"CLIP {self._clip_slider.value:.2f}")
        if self._bw_slider.handle_event(ev):
            cmds.append(f"BW {self._bw_slider.int_value}")
        if self._stop_all_btn.handle_event(ev):
            cmds.append("STOP")
        return cmds

    def draw(self, surface: pygame.Surface,
             font_lg: pygame.font.Font, font_sm: pygame.font.Font) -> None:
        for voice in self.voices:
            voice.draw(surface, font_lg, font_sm)
        pygame.draw.line(surface, ACCENT,
                         (0, self._bot_y), (self.W, self._bot_y))
        self._vol_slider.draw(surface, font_sm)
        self._clip_slider.draw(surface, font_sm)
        self._bw_slider.draw(surface, font_sm)
        self._stop_all_btn.draw(surface, font_sm)


# ── Visualizer ────────────────────────────────────────────────────────────────
class Visualizer:
    def __init__(self, fullscreen: bool = True, width: int = 1280, height: int = 720):
        pygame.init()
        pygame.display.set_caption(TITLE)
        pygame.mouse.set_visible(True)

        if fullscreen:
            self.screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
        else:
            self.screen = pygame.display.set_mode((width, height))

        self.W, self.H = self.screen.get_size()
        self.font_lg = pygame.font.SysFont("monospace", 26, bold=True)
        self.font_sm = pygame.font.SysFont("monospace", 17)
        self.clock   = pygame.time.Clock()

        # ── Shared header ─────────────────────────────────────────────────────
        hdr_h = 58
        self.hdr_rect = pygame.Rect(0, 0, self.W, hdr_h)

        # ── Tab buttons (right side of header) ───────────────────────────────
        tab_w, tab_h = 160, 36
        tab_y = (hdr_h - tab_h) // 2
        self._tab_spectrum = Button(
            pygame.Rect(self.W - 2 * tab_w - 20, tab_y, tab_w, tab_h),
            "< SPECTRUM",
        )
        self._tab_controls = Button(
            pygame.Rect(self.W - tab_w - 10,       tab_y, tab_w, tab_h),
            "CONTROLS >",
        )
        self._tab_spectrum.active = True
        self._tab_controls.active = False

        # ── Spectrum screen layout ────────────────────────────────────────────
        ctrl_h = 80
        inner  = self.H - hdr_h - ctrl_h
        wave_h = int(inner * 0.42)
        fft_h  = inner - wave_h

        self.wave_rect = pygame.Rect(0, hdr_h,           self.W, wave_h)
        self.fft_rect  = pygame.Rect(0, hdr_h + wave_h,  self.W, fft_h)
        self.ctrl_rect = pygame.Rect(0, self.H - ctrl_h, self.W, ctrl_h)

        self._fill_surf = pygame.Surface((self.W, fft_h), pygame.SRCALPHA)

        # ── Spectrum display sliders + trigger controls ────────────────────────
        pad    = 30
        gap    = 20
        trig_btn_w = 100
        # 3 sliders + trigger level slider + trigger button
        avail  = self.W - 2 * pad - 4 * gap - trig_btn_w
        s_w    = avail // 4
        s_y    = self.ctrl_rect.top + 6
        s_h    = ctrl_h - 10

        x = pad
        self._amp_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="Amplitude", min_val=0.1, max_val=10.0, init_val=1.0,
            log=True, fmt="{:.2f}", unit="x",
        )
        x += s_w + gap
        self._time_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="Time window", min_val=4.0, max_val=128.0, init_val=32.0,
            log=True, fmt="{:.0f}", unit=" ms",
        )
        x += s_w + gap
        self._freq_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="Max frequency", min_val=200.0, max_val=20000.0, init_val=20000.0,
            log=True, fmt="{:.0f}", unit=" Hz",
        )
        x += s_w + gap
        self._trig_level_slider = Slider(
            pygame.Rect(x, s_y, s_w, s_h),
            label="Trig level", min_val=-1.0, max_val=1.0, init_val=0.0,
            fmt="{:.2f}",
        )
        x += s_w + gap
        btn_h = min(36, s_h - 8)
        btn_y = self.ctrl_rect.top + (ctrl_h - btn_h) // 2
        self._trig_btn = Button(
            pygame.Rect(x, btn_y, trig_btn_w, btn_h),
            "TRIG: OFF",
            active_color=TRIG_COL,
            text_color=TEXT_COL,
        )
        self._trig_modes = ("OFF", "AUTO")
        self._trig_mode_idx = 0

        self._spec_sliders = (self._amp_slider, self._time_slider,
                              self._freq_slider, self._trig_level_slider)

        # ── Controls screen ───────────────────────────────────────────────────
        self._controls = ControlsScreen(self.W, self.H, hdr_h)

        # ── State ─────────────────────────────────────────────────────────────
        self._active_screen  = Screen.SPECTRUM
        self.paused          = False
        self._cmd_queue: list[str] = []

    # ── Properties ────────────────────────────────────────────────────────────

    @property
    def n_samples(self) -> int:
        """Number of waveform samples to request (time window × 48 kHz)."""
        return max(2, int(self._time_slider.value * 48))

    @property
    def trigger_mode(self) -> str:
        """Current trigger mode: 'OFF', 'AUTO', or 'NORMAL'."""
        return self._trig_modes[self._trig_mode_idx]

    @property
    def trigger_level(self) -> float:
        """Trigger level normalised to [-1, 1]."""
        return self._trig_level_slider.value

    # ── Public API ────────────────────────────────────────────────────────────

    def get_pending_commands(self) -> list[str]:
        """Drain and return ESP32 commands queued by the controls screen."""
        cmds = self._cmd_queue[:]
        self._cmd_queue.clear()
        return cmds

    def draw(self, waveform: np.ndarray, fft_db: np.ndarray, freqs: np.ndarray,
             status: str = "") -> None:
        self.screen.fill(BG)
        self._draw_header(status)

        if self._active_screen == Screen.SPECTRUM:
            if self.paused:
                self._draw_paused_overlay()
            else:
                self._draw_waveform(waveform)
                self._draw_fft(fft_db, freqs)
            self._draw_spec_controls()
        else:
            self._controls.draw(self.screen, self.font_lg, self.font_sm)

        pygame.display.flip()

    def process_events(self) -> bool:
        """Return False when the user wants to quit."""
        for ev in pygame.event.get():
            if ev.type == pygame.QUIT:
                return False
            if ev.type == pygame.KEYDOWN:
                if ev.key in (pygame.K_ESCAPE, pygame.K_q):
                    return False
                if ev.key == pygame.K_TAB:
                    self._toggle_screen()

            # Tab buttons always active — live in the shared header
            if self._tab_spectrum.handle_event(ev):
                self._set_screen(Screen.SPECTRUM)
            if self._tab_controls.handle_event(ev):
                self._set_screen(Screen.CONTROLS)

            if self._active_screen == Screen.SPECTRUM:
                slider_hit = any(s.handle_event(ev) for s in self._spec_sliders)

                # Trigger mode button cycles OFF → AUTO → NORMAL → OFF
                if self._trig_btn.handle_event(ev):
                    self._trig_mode_idx = (self._trig_mode_idx + 1) % len(self._trig_modes)
                    self._trig_btn.label  = f"TRIG: {self.trigger_mode}"
                    self._trig_btn.active = (self._trig_mode_idx != 0)
                    slider_hit = True   # prevent pause toggle

                if not slider_hit and ev.type == pygame.MOUSEBUTTONDOWN:
                    in_tab = (self._tab_spectrum.rect.collidepoint(ev.pos) or
                              self._tab_controls.rect.collidepoint(ev.pos))
                    if ev.button == 1 and not in_tab:
                        self.paused = not self.paused
                    elif ev.button == 3:
                        return False
            else:
                cmds = self._controls.handle_event(ev)
                self._cmd_queue.extend(cmds)

        return True

    def tick(self, fps: int = 30) -> None:
        self.clock.tick(fps)

    def get_fps(self) -> float:
        return self.clock.get_fps()

    def quit(self) -> None:
        pygame.quit()

    # ── Private helpers ───────────────────────────────────────────────────────

    def _set_screen(self, s: Screen) -> None:
        self._active_screen       = s
        self._tab_spectrum.active = (s == Screen.SPECTRUM)
        self._tab_controls.active = (s == Screen.CONTROLS)

    def _toggle_screen(self) -> None:
        self._set_screen(
            Screen.CONTROLS if self._active_screen == Screen.SPECTRUM
            else Screen.SPECTRUM
        )

    def _draw_header(self, status: str) -> None:
        r = self.hdr_rect
        pygame.draw.line(self.screen, ACCENT, (0, r.bottom - 1), (self.W, r.bottom - 1))

        # Title (left)
        title_s = self.font_lg.render(TITLE, True, TITLE_COL)
        self.screen.blit(title_s, (20, (r.height - title_s.get_height()) // 2))

        # FPS / stats — between title and tab buttons
        fps    = self.get_fps()
        rt     = f"{status}  {fps:.0f} fps" if status else f"{fps:.0f} fps"
        rt_s   = self.font_sm.render(rt, True, TEXT_COL)
        tab_lx = self._tab_spectrum.rect.left - 20
        self.screen.blit(rt_s, (tab_lx - rt_s.get_width() - 10,
                                 (r.height - rt_s.get_height()) // 2))

        # Tab buttons
        self._tab_spectrum.draw(self.screen, self.font_sm)
        self._tab_controls.draw(self.screen, self.font_sm)

    def _draw_paused_overlay(self) -> None:
        overlay = pygame.Surface((self.W, self.H), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 160))
        self.screen.blit(overlay, (0, 0))
        msg = self.font_lg.render("PAUSED  —  click to resume", True, TITLE_COL)
        self.screen.blit(msg, ((self.W - msg.get_width()) // 2,
                                (self.H - msg.get_height()) // 2))

    def _draw_spec_controls(self) -> None:
        pygame.draw.line(self.screen, ACCENT, (0, self.ctrl_rect.top),
                         (self.W, self.ctrl_rect.top))
        for s in self._spec_sliders:
            s.draw(self.screen, self.font_sm)
        self._trig_btn.draw(self.screen, self.font_sm)

    def _draw_waveform(self, waveform: np.ndarray) -> None:
        r       = self.wave_rect
        amp     = self._amp_slider.value
        mid_y   = r.centery
        draw_x0 = r.left + LABEL_PAD
        draw_w  = r.width - LABEL_PAD
        draw_h  = r.height - 20

        lbl = self.font_sm.render("WAVEFORM", True, WAVE_COL)
        self.screen.blit(lbl, (draw_x0, r.top + 5))

        for frac in (1.0, 0.5, 0.0, -0.5, -1.0):
            y = int(mid_y - frac * draw_h / 2)
            if not (r.top + 2 <= y <= r.bottom - 2):
                continue
            pygame.draw.line(self.screen, GRID, (draw_x0, y), (r.right, y))
            v    = frac / amp
            text = "0" if abs(v) < 1e-9 else f"{v:+.2g}"
            ls   = self.font_sm.render(text, True, GRID)
            self.screen.blit(ls, (r.left + 2, y - ls.get_height() // 2))

        pygame.draw.line(self.screen, ACCENT, (0, r.bottom), (self.W, r.bottom))

        # Trigger level line (yellow dashed) when trigger is active
        if self._trig_mode_idx != 0:
            trig_y = int(mid_y - self.trigger_level * amp * (draw_h / 2))
            trig_y = max(r.top + 2, min(r.bottom - 2, trig_y))
            # Draw dashed line
            dash_len = 10
            for dx in range(draw_x0, r.right, dash_len * 2):
                x_end = min(dx + dash_len, r.right)
                pygame.draw.line(self.screen, TRIG_COL, (dx, trig_y), (x_end, trig_y), 1)
            # Small triangle marker on left edge
            tri_x = draw_x0 - 2
            pygame.draw.polygon(self.screen, TRIG_COL, [
                (tri_x, trig_y),
                (tri_x - 10, trig_y - 6),
                (tri_x - 10, trig_y + 6),
            ])
            # Mode label top-right of waveform panel
            mode_lbl = self.font_sm.render(f"TRIG: {self.trigger_mode}", True, TRIG_COL)
            self.screen.blit(mode_lbl, (r.right - mode_lbl.get_width() - 10, r.top + 5))

        if len(waveform) < 2:
            return

        n  = len(waveform)
        xs = np.linspace(draw_x0, r.right - 1, n).astype(int)
        ys = (mid_y - waveform * amp * (draw_h / 2)).astype(int)
        ys = np.clip(ys, r.top + 2, r.bottom - 2)
        pygame.draw.lines(self.screen, WAVE_COL, False,
                          list(zip(xs.tolist(), ys.tolist())), 2)

    def _draw_fft(self, fft_db: np.ndarray, freqs: np.ndarray) -> None:
        r        = self.fft_rect
        max_freq = max(200, self._freq_slider.int_value)
        draw_x0  = r.left + LABEL_PAD
        draw_w   = r.width - LABEL_PAD
        draw_bot = r.bottom - 22
        draw_h   = draw_bot - r.top - 26

        lbl = self.font_sm.render("SPECTRUM (FFT)", True, FFT_COL)
        self.screen.blit(lbl, (draw_x0, r.top + 5))

        def db_to_y(db: float) -> int:
            frac = (db - DB_MIN) / (DB_MAX - DB_MIN)
            return int(draw_bot - frac * draw_h)

        for db in (-60, -40, -20, 0):
            y = db_to_y(db)
            if r.top + 20 <= y <= draw_bot:
                pygame.draw.line(self.screen, GRID, (draw_x0, y), (r.right, y))
                ls = self.font_sm.render(f"{db:+d}", True, GRID)
                self.screen.blit(ls, (r.left + 2, y - ls.get_height() // 2))

        for f in FREQ_TICKS:
            if f > max_freq:
                break
            x = draw_x0 + int(f / max_freq * draw_w)
            pygame.draw.line(self.screen, GRID, (x, r.top + 24), (x, draw_bot))
            lbl_f = f"{f // 1000}k" if f >= 1000 else str(f)
            ls = self.font_sm.render(lbl_f, True, GRID)
            self.screen.blit(ls, (x - ls.get_width() // 2, draw_bot + 3))

        if len(fft_db) < 2 or len(freqs) < 2:
            return

        mask   = freqs <= max_freq
        f_sel  = freqs[mask]
        db_sel = np.clip(fft_db[mask], DB_MIN, DB_MAX)

        if len(f_sel) < 2:
            return

        xs = (draw_x0 + f_sel / max_freq * draw_w).astype(int)
        ys = np.array([db_to_y(float(d)) for d in db_sel], dtype=int)
        ys = np.clip(ys, r.top + 24, draw_bot)

        self._fill_surf.fill((0, 0, 0, 0))
        poly = ([(int(xs[0]),  draw_bot - r.top)]
                + [(int(x), int(y) - r.top) for x, y in zip(xs, ys)]
                + [(int(xs[-1]), draw_bot - r.top)])
        pygame.draw.polygon(self._fill_surf, (*FFT_COL, 45), poly)
        self.screen.blit(self._fill_surf, (0, r.top))

        pts = list(zip(xs.tolist(), ys.tolist()))
        if len(pts) >= 2:
            pygame.draw.lines(self.screen, FFT_COL, False, pts, 2)
